services:
  postgres:
    image: postgres
    container_name: ecommerce_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hdev
      - POSTGRES_PASSWORD=123456
    volumes:
      - /ecommerce/data/postgres

  mongodb:
    image: mongo
    container_name: ecommerce_mongodb
    ports:
      - "27017:27017"
    volumes:
      - /ecommerce/data/mongodb

  redis:
    image: redis
    container_name: ecommerce_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.1.6-management
    container_name: ecommerce_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"